spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncode=utf8
    username: root
    password: yxc686979y
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.hotel.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

